language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: "pip install ."
before_script:
  - pip install python-coveralls pytest-cov
# command to run tests
script: py.test --cov=melting
after_success:
  - coveralls